site_name: Neighbourhood Watch Canada
nav:
    - Home: index.md
    # - Architecture: architecture.md
    # - Hardware: parts.md
    - Installation:
        - Backend: installation/backend.md
        - Frontend: installation/frontend.md
    - Reference:
        - Environment Variables: reference/environment-variables.md
        - API: reference/api.md
theme: readthedocs
