site_name: NWApp Documenation
nav:
    - Home: index.md
    - Backend Production Installation:
        - DigitalOcean Droplet: backend-install/1-DigitalOcean-Droplet.md
        - Virtual Hosts: backend-install/2-Virtual-Hosts.md
        - Application: backend-install/3-Application.md
        - SSL: backend-install/4-Lets-Encrypt.md
        - Swap Memory: backend-install/5-Swap-Memory.md
theme: readthedocs
