site_name: Neighbourhood Watch Canada
nav:
    - Home: index.md
    # - Architecture: architecture.md
    # - Hardware: parts.md
    # - Installation:
    #     - Device: installation/device.md
    #     - Serial Communication: installation/serial_communication.md
    #     - Services: installation/services.md
    # - Usage:
    #     - Nameserver: usage/nameserver.md
    #     - Storage: usage/storage.md
    #     - Instruments: usage/instruments.md
    #     - Logging: usage/logging.md
    #     - Remote: usage/remote.md
    #     - Serial: usage/serial.md
    # - Reference:
    #     - Environment Variables: reference/environment_variables.md
theme: readthedocs
